# Generated by Django 3.0.3 on 2020-02-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20200209_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListHRDatabaseUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuid', models.CharField(db_column='CG_ML_HR_OBS_CUID', max_length=11)),
                ('source', models.CharField(db_column='CG_ML_HR_OBS_SOURCE', max_length=4, null=True)),
                ('location', models.CharField(db_column='CM_STP_LOCATION_ID', max_length=10)),
                ('department', models.CharField(db_column='CM_STP_DEPTID', max_length=10)),
                ('reg_temp', models.CharField(db_column='CG_ML_HR_OBS_REGTMP', max_length=30, null=True)),
                ('empl_status', models.CharField(db_column='CG_ML_HR_OBS_EMPLSTATUS', max_length=1, null=True)),
                ('empl_description', models.CharField(db_column='CG_ML_HR_OBS_EMPLSTATUS_DESC', max_length=50, null=True)),
                ('empl_class', models.CharField(db_column='CG_ML_HR_OBS_EMPL_CLASS', max_length=10)),
                ('first_name', models.CharField(db_column='CG_ML_HR_OBS_FIRST_NM', max_length=255, null=True)),
                ('pref_first_name', models.CharField(db_column='CG_ML_HR_OBS_PREF_FIRST_NM', max_length=255, null=True)),
                ('middle_name', models.CharField(db_column='CG_ML_HR_OBS_MIDDLE_NM', max_length=255, null=True)),
                ('last_name', models.CharField(db_column='CG_ML_HR_OBS_LAST_NM', max_length=255, null=True)),
                ('pref_last_name', models.CharField(db_column='CG_ML_HR_OBS_PREF_LAST_NM', max_length=255, null=True)),
                ('prefix', models.CharField(db_column='CG_ML_HR_OBS_PREFIX', max_length=255, null=True)),
                ('email', models.CharField(db_column='CG_ML_HR_OBS_EMAIL', max_length=255, null=True)),
                ('is_supervisor_mngr', models.BooleanField(db_column='CG_ML_HR_OBS_IS_SUP_MGR', default=False)),
                ('is_functional_mngr', models.BooleanField(db_column='CG_ML_HR_OBS_IS_FUNC_MGR', default=False)),
                ('refresh_date_time', models.DateTimeField(auto_now_add=True, db_column='CG_ENTRY_CREATION_DATE_TIME')),
                ('legal_type', models.CharField(db_column='CG_ML_HR_OBS_LEGAL_TYPE', max_length=255, null=True)),
                ('eq_leg_entity_desc', models.CharField(db_column='CG_ML_HR_OBS_EQ_LEG_ENTITY_DESC', max_length=255, null=True)),
                ('eq_rcv_comm_flag', models.BooleanField(db_column='CG_ML_HR_OBS_EQ_RCV_COMM_FLG', default=False)),
                ('hr_flag', models.CharField(blank=True, db_column='CG_ML_HR_OBS_FLAG', default='', max_length=15, null=True)),
                ('ofcr_code', models.CharField(blank=True, db_column='CG_ML_HR_OBS_OFCR_CD', default='', max_length=2)),
                ('company_id', models.CharField(blank=True, db_column='CG_ML_HR_OBS_COMPANY_ID', default='', max_length=50)),
                ('company_desc', models.CharField(blank=True, db_column='CG_ML_HR_OBS_COMPANY_desc', default='', max_length=255)),
                ('location_desc', models.CharField(blank=True, db_column='CG_ML_HR_OBS_LOCATION_DESCR', default='', max_length=255)),
                ('emptype_desc', models.CharField(blank=True, db_column='CG_ML_HR_OBS_EMPL_TYPE_DESCR', default='', max_length=255)),
                ('country', models.CharField(blank=True, db_column='CG_ML_HR_OBS_COUNTRY', default='', max_length=255)),
                ('region', models.CharField(blank=True, db_column='CG_ML_HR_OBS_REGION', default='', max_length=255)),
                ('descr200', models.CharField(blank=True, db_column='CG_ML_HR_OBS_DESCR200', default='', max_length=255)),
                ('descr2000', models.CharField(blank=True, db_column='CG_ML_HR_OBS_DESCR2000', default='', max_length=2000)),
                ('dept_name', models.CharField(blank=True, db_column='CG_ML_HR_OBS_DEPTNAME', default='', max_length=255)),
                ('city', models.CharField(blank=True, db_column='CG_ML_HR_OBS_CITY', default='', max_length=255)),
                ('supervisor_mngr_cuid', models.CharField(blank=True, db_column='CG_ML_HR_SUP_MGR_CUID', default='', max_length=255)),
                ('supervisor_mngr_email', models.CharField(blank=True, db_column='CG_ML_HR_SUP_MGR_EMAIL', default='', max_length=255)),
                ('functional_mngr_cuid', models.CharField(blank=True, db_column='CG_ML_HR_FUNC_MGR_CUID', default='', max_length=255)),
                ('functional_mngr_email', models.CharField(blank=True, db_column='CG_ML_HR_FUNC_MGR_EMAIL', default='', max_length=255)),
                ('per_org', models.CharField(blank=True, db_column='CG_ML_HR_PER_ORG', default='', max_length=255)),
                ('termination_date', models.DateField(db_column='CG_ML_HR_TERMINATION_DATE', null=True)),
                ('contract_end_date', models.DateField(db_column='CG_ML_HR_CONTRACT_END_DATE', null=True)),
            ],
            options={
                'db_table': 'CM_Mailing_list_HR_DB_Users_tbl',
            },
        ),
    ]
