# Generated by Django 3.0.3 on 2020-02-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_mailinglisthrdatabaseusers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='snippet',
            table='CM_Snippet_tbl',
        ),
    ]
